#:import AvatarImage components.avatar_image.AvatarImage

<OnlineAvatarImage>
    size_hint: None, None
    md_bg_color: 1, 1, 1, 1
    size: 40, 40

    AvatarImage:
        source: root.avatar
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    # Green icon represents online
    FitImage:
        source: "assets/images/green.png"
        size_hint: None, None
        size: 10, 10
        pos_hint: {'x': 0.75, 'y': 0.0}